### ISSUE TITLE
Separate list for back and forward button

### ISSUE THREAD

**Issue by vanowm** [vanowm/BackForwardHistoryTweaks#12]
An option to split history list so it would only display back history when clicked on back button and forward history on forward button.

**Comment by xevidencex** [comment]
Please create it independently, even with legacy issues, you shouldn't worry about it,
i use an older version of firefox & i know how to bypass it if it's just a legacy issue.
you don't have to post the file on amo, it can be anywhere.
__

Sorry, can't create an addon for it, because mozilla no longer accepts "legacy" addons and it's impossible to do with WebExtension.

However v1.6 has this feature now (just submitted, awaiting review)

Regards, V.

**Comment by vanowm** [comment]
And what would be the point of doing that? Just leave all options default and use the option you need.

**Comment by xevidencex** [comment]
it's like having a lot of useless code each time i install a new addon ((
if it's not too hard, i'd like it to hae that only function in an addon
i can confirm it works anyways, after a restart.

**Comment by xevidencex** [comment]
Error:

1) left button behavior:
-if i move back to the first browsed site (site at the bottom of the list)
-it goes straight to that page.

2) right button behavior:
-if i move forward to the last browsed site (site at the bottom of the list)
-it goes TO THE NET SITE..
-if i move forward to the last browsed site (site at the bottom of the list) [AGAIN]
-it goes TO THE NEXT SITE again.. Until reaching the requested last browsed site
-(clicking on forward button's last browsed site, leads you to the next site till you reach
that site by clicking over & over..

**Comment by vanowm** [comment]
Right click in the popup menu no longer works as expected (re-opening issue #4)

It still works fine in FF52 ESR

**Comment by xevidencex** [comment]
I am not a firefox "shoot all past programmers coding time & available work
since decades" new intellectual "design",
i will not move to 52 to ruin tones of addons, scripts & co.

I'm on v44.0.2

**Comment by xevidencex** [comment]
please send me just the separate history on buttons "functionality"
if not complicated in an independant addon, or even a greasemonkey script if possible

**Comment by vanowm** [comment]
Feel free learn how to make your own addons and get the needed code from this addon.

That's how I started when found lack of customization I wanted.

**Comment by xevidencex** [comment]
carelessness.. ok, i'll have to keep asking others
