### ISSUE TITLE
History items shown as url when TabMix Plus is enabled.

### ISSUE THREAD

**Issue by vanowm** [vanowm/BackForwardHistoryTweaks#6]

**Comment by vanowm** [comment]
I'm not sure how this was working properly in previous versions, unless something changed in TMP very recently..

**Comment by onemen** [comment]
bootstrap.js > FillHistoryMenu
fix the call to window.TMP_Places.getTitleFromBookmark

replace 
window.TMP_Places.getTitleFromBookmark(e.url)
with
window.TMP_Places.getTitleFromBookmark(e.url, e.titled)

**Comment by vanowm** [comment]
Thanks, it was already fixed in v1.4.1
