### ISSUE TITLE
Make 'None' and option

### ISSUE THREAD

**Issue by bbooyydd** [vanowm/BackForwardHistoryTweaks#9]
Feature request.
I find the back/forward popup annoying and have not found a way to turn it off completely.  If your add-on included a way to disable the popup (a none or zero option), I would appreciate that.

**Comment by vanowm** [comment]
If you just left click on back/forward buttons there is no popup.

**Comment by bbooyydd** [comment]
Nope.  First left click was bringing up the menu. Second left click takes me back one step back without needing the menu.  May be a setting thing that happened via some add-on.  But I found an Back/Forward History off check box in Classic Theme Restorer that turn off the history popup, an that got me back to the behavior I wanted.  Thanks anyway.

**Comment by vanowm** [comment]
What browser, os?
I don't have this functionality in any Firefox on Windows 7/10
Perhaps it's some other browser's settings that you've changed?

I know click and hold left mouse button would open popup menu, but not single click.

**Comment by bbooyydd** [comment]
Firefox, Windows 10.  Seemed to start on recent Firefox update to 47.0 
but not sure.  I'm not concerned now because a setting in 'Classic Theme 
Restorer' shut it off.  I like all my navigation buttons clustered on 
the left.

With popup.



Setting that stopped popup.



Best wishes,
Randy

**Comment by vanowm** [comment]
So, is the popup issue actually this addon related? can you confirm it by disabling all other addons, leaving only this addon enabled?

**Comment by bbooyydd** [comment]
No.  I tried to use your app to fix it.  My post was a feature request 
only.  If found the feature in Classic Theme Restorer. Uninstalled your app.

**Comment by vanowm** [comment]
Then you probably should find the source of this instead of looking for a work around, because what you've described is not something Firefox does by default.

Disabling popup would defeat the whole point of this extension.
